// Hotel loyalty programmes shown on the hotel search page, with booking links.
// Point values come from the catalog (src/data/catalog/valuations.json).
export const HOTEL_PROGRAM_LINKS = [
  { name: 'World of Hyatt', slug: 'hyatt', color: '#002147', logo: '🏨', note: 'Usually the best hotel points value. Standard award chart. 5-tier update May 2026.', searchUrl: 'https://www.hyatt.com/search', roomsAero: 'https://rooms.aero?program=hyatt', buildUrl: (dest: string, checkIn: string, checkOut: string) => `https://www.hyatt.com/search?destination=${encodeURIComponent(dest)}&checkInDate=${checkIn}&checkOutDate=${checkOut}&useRewardPoints=true` },
  { name: 'Marriott Bonvoy', slug: 'marriott', color: '#cc0000', logo: '🏨', note: 'Largest network (30+ brands). Dynamic pricing. 5th night free on awards.', searchUrl: 'https://www.marriott.com/search/findHotels.mi', roomsAero: 'https://rooms.aero?program=marriott', buildUrl: (dest: string, checkIn: string, checkOut: string) => `https://www.marriott.com/search/findHotels.mi?destinationAddress.destination=${encodeURIComponent(dest)}&fromDate=${checkIn}&toDate=${checkOut}` },
  { name: 'Hilton Honors', slug: 'hilton', color: '#1E3A8A', logo: '🏨', note: 'Easy to earn (Amex transfers at 1:2). 5th night free.', searchUrl: 'https://www.hilton.com/en/search/?redeemPts=true', roomsAero: 'https://rooms.aero?program=hilton', buildUrl: (dest: string, checkIn: string, checkOut: string) => `https://www.hilton.com/en/search/?query=${encodeURIComponent(dest)}&arrivalDate=${checkIn}&departureDate=${checkOut}&redeemPts=true` },
  { name: 'IHG One Rewards', slug: 'ihg', color: '#6a994e', logo: '🏨', note: 'Underrated. 4th night free on awards.', searchUrl: 'https://www.ihg.com/hotels/us/en/find-hotels/hotel/list', roomsAero: 'https://rooms.aero?program=ihg', buildUrl: (dest: string, checkIn: string, checkOut: string) => `https://www.ihg.com/hotels/us/en/find-hotels/hotel/list?qDest=${encodeURIComponent(dest)}&qCiD=${checkIn}&qCoD=${checkOut}&setPMCookies=true` },
  { name: 'Choice Privileges', slug: 'choice', color: '#0072CE', logo: '🏨', note: 'Good for budget properties.', searchUrl: 'https://www.choicehotels.com/use-points', roomsAero: 'https://rooms.aero?program=choice', buildUrl: (_dest: string, _checkIn: string, _checkOut: string) => 'https://www.choicehotels.com/use-points' },
]
